name: Build and test 🧪

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x            

      - name: Build the package
        run: dotnet build src/AzureFunction.Isolated.HostConfigurator/AzureFunction.Isolated.HostConfigurator.csproj --configuration Release

      - name: Configure global dotnet source
        run: dotnet nuget add source ${{ github.workspace }}/src/AzureFunction.Isolated.HostConfigurator/bin/Release -n local 

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-restore --no-build --verbosity normal --configuration Release
        