name: Publish NuGet Package ⚒️

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x        

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion # id to be referenced in the next step
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          targetPath: src/AzureFunction.Isolated.HostConfigurator
          additionalArguments: '/updateprojectfiles=true'

      - name: Build the package
        run: dotnet build src/AzureFunction.Isolated.HostConfigurator/AzureFunction.Isolated.HostConfigurator.csproj --configuration Release

      - name: Build package
        run: dotnet pack src/AzureFunction.Isolated.HostConfigurator/AzureFunction.Isolated.HostConfigurator.csproj --configuration Release -o ./artifacts 

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{steps.gitversion.outputs.SemVer}}
          prerelease: false
          title: 'Release version ${{steps.gitversion.outputs.SemVer}}'

      # - name: Publish package
      #   run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
